/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/models/hoth/battle_of_hoth.glb 
Author: Demosk Omicron (https://sketchfab.com/demoskOmicron)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/battle-of-hoth-diorama-ff30e517dd0041a0a2b96dd47f50dda6
Title: Battle of Hoth Diorama
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'

export function BattleHoth(props) {
  const { nodes, materials } = useGLTF('./models/ep5/hoth/battle_of_hoth.glb')
  const [modelLoaded, setModelLoaded] = useState(false);

  useEffect(() => {
    const timeoutId = setTimeout(() => {
      setModelLoaded(true);
    }, 50000);

    // Limpiar el temporizador si el componente se desmonta antes de que se cargue el modelo
    return () => clearTimeout(timeoutId);
  }, []); // El array vacío asegura que este efecto se ejecute solo una vez al montar el componente

  if (!modelLoaded) {
    return null; // O puedes devolver un indicador de carga aquí
  }
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.116}>
        <group position={[-0.194, 0, 3.33]} scale={0.251}>
          <mesh geometry={nodes.Cube001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cube001_1.geometry} material={materials.material} />
          <mesh geometry={nodes.Cube001_2.geometry} material={materials.Negros_Intensos} />
        </group>
        <group position={[-0.855, 2.911, -1.035]} scale={[-10.518, 13.26, 1]}>
          <mesh geometry={nodes.Cube048_0.geometry} material={materials.Material} />
          <mesh geometry={nodes.Cube048_0_1.geometry} material={materials.Material} />
          <mesh geometry={nodes.Cube048_0_2.geometry} material={materials.Material} />
        </group>
        <group position={[-0.199, -4.773, 3.287]} rotation={[-Math.PI, -1.571, 0]} scale={[0.4, 0.379, 0.4]}>
          <mesh geometry={nodes.BezierCurve094_0.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.BezierCurve094_1.geometry} material={materials.Negros_Intensos} />
          <mesh geometry={nodes.BezierCurve094_2.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.BezierCurve094_3.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.BezierCurve094_4.geometry} material={materials['Color_Detalle_X-Wing']} />
        </group>
        <group position={[-0.203, -4.528, 3.289]} rotation={[-Math.PI, -1.571, 0]} scale={[0.4, 0.379, 0.4]}>
          <mesh geometry={nodes.BezierCurve095_0.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.BezierCurve095_1.geometry} material={materials.Negros_Intensos} />
          <mesh geometry={nodes.BezierCurve095_2.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.BezierCurve095_3.geometry} material={materials['Color_Detalle_X-Wing']} />
        </group>
        <group position={[-0.203, -4.88, 3.301]} rotation={[0, 0, 3.141]} scale={[0.185, 0.362, 0.13]}>
          <mesh geometry={nodes.Cube050_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cube050_1.geometry} material={materials['Color_Detalle_X-Wing']} />
          <mesh geometry={nodes.Cube050_2.geometry} material={materials.Negros_Intensos} />
          <mesh geometry={nodes.Cube050_3.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Cube050_4.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Cube050_5.geometry} material={materials['Material.004']} />
        </group>
        <group position={[-0.143, -4.627, 3.451]} rotation={[-Math.PI, 0, -3.141]} scale={[-0.049, 0.049, 0.049]}>
          <mesh geometry={nodes.Sphere007_0.geometry} material={materials['Material.006']} />
          <mesh geometry={nodes.Sphere007_1.geometry} material={materials['Material.008']} />
          <mesh geometry={nodes.Sphere007_2.geometry} material={materials.Negros_Intensos} />
          <mesh geometry={nodes.Sphere007_3.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Sphere007_4.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Sphere007_5.geometry} material={materials['Material.011']} />
        </group>
        <group position={[4.585, 4.656, 3.607]} rotation={[-3.042, -0.57, -3.141]} scale={[-0.049, 0.049, 0.049]}>
          <mesh geometry={nodes.Sphere008_0.geometry} material={materials['Material.006']} />
          <mesh geometry={nodes.Sphere008_1.geometry} material={materials['Material.008']} />
          <mesh geometry={nodes.Sphere008_2.geometry} material={materials.Negros_Intensos} />
          <mesh geometry={nodes.Sphere008_3.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Sphere008_4.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Sphere008_5.geometry} material={materials['Material.011']} />
        </group>
        <group position={[4.454, 4.413, 3.489]} rotation={[0.1, 0.57, 3.141]} scale={[0.185, 0.362, 0.13]}>
          <mesh geometry={nodes.Cube051_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cube051_1.geometry} material={materials['Color_Detalle_X-Wing']} />
          <mesh geometry={nodes.Cube051_2.geometry} material={materials.Negros_Intensos} />
          <mesh geometry={nodes.Cube051_3.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Cube051_4.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Cube051_5.geometry} material={materials['Material.004']} />
        </group>
        <group position={[4.447, 4.764, 3.513]} rotation={[0.099, -1.001, 3.141]} scale={[0.4, 0.379, 0.4]}>
          <mesh geometry={nodes.BezierCurve096_0.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.BezierCurve096_1.geometry} material={materials.Negros_Intensos} />
          <mesh geometry={nodes.BezierCurve096_2.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.BezierCurve096_3.geometry} material={materials['Color_Detalle_X-Wing']} />
        </group>
        <group position={[4.45, 4.521, 3.485]} rotation={[0.099, -1.001, 3.141]} scale={[0.4, 0.379, 0.4]}>
          <mesh geometry={nodes.BezierCurve097_0.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.BezierCurve097_1.geometry} material={materials.Negros_Intensos} />
          <mesh geometry={nodes.BezierCurve097_2.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.BezierCurve097_3.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.BezierCurve097_4.geometry} material={materials['Color_Detalle_X-Wing']} />
        </group>
        <group position={[-8.306, 0.798, 0.313]} rotation={[2.613, -1.349, -0.356]} scale={[0.4, 0.379, 0.4]}>
          <mesh geometry={nodes.BezierCurve098_0.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.BezierCurve098_1.geometry} material={materials.Negros_Intensos} />
          <mesh geometry={nodes.BezierCurve098_2.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.BezierCurve098_3.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.BezierCurve098_4.geometry} material={materials['Color_Detalle_X-Wing']} />
        </group>
        <group position={[-8.329, 1.038, 0.27]} rotation={[2.613, -1.349, -0.356]} scale={[0.4, 0.379, 0.4]}>
          <mesh geometry={nodes.BezierCurve099_0.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.BezierCurve099_1.geometry} material={materials.Negros_Intensos} />
          <mesh geometry={nodes.BezierCurve099_2.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.BezierCurve099_3.geometry} material={materials['Color_Detalle_X-Wing']} />
        </group>
        <group position={[-8.304, 0.695, 0.345]} rotation={[-0.164, -0.208, -3.063]} scale={[0.185, 0.362, 0.13]}>
          <mesh geometry={nodes.Cube052_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cube052_1.geometry} material={materials['Color_Detalle_X-Wing']} />
          <mesh geometry={nodes.Cube052_2.geometry} material={materials.Negros_Intensos} />
          <mesh geometry={nodes.Cube052_3.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Cube052_4.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Cube052_5.geometry} material={materials['Material.004']} />
        </group>
        <group position={[-8.296, 0.974, 0.455]} rotation={[2.977, 0.208, 3.063]} scale={[-0.049, 0.049, 0.049]}>
          <mesh geometry={nodes.Sphere009_0.geometry} material={materials['Material.006']} />
          <mesh geometry={nodes.Sphere009_1.geometry} material={materials['Material.008']} />
          <mesh geometry={nodes.Sphere009_2.geometry} material={materials.Negros_Intensos} />
          <mesh geometry={nodes.Sphere009_3.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Sphere009_4.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Sphere009_5.geometry} material={materials['Material.011']} />
        </group>
        <group position={[-3.639, 1.959, 3.33]} scale={0.251}>
          <mesh geometry={nodes.Cube067_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cube067_1.geometry} material={materials.material} />
          <mesh geometry={nodes.Cube067_2.geometry} material={materials.Negros_Intensos} />
        </group>
        <group position={[2.897, 5.314, 3.33]} scale={0.251}>
          <mesh geometry={nodes.Cube068_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cube068_1.geometry} material={materials.material} />
          <mesh geometry={nodes.Cube068_2.geometry} material={materials.Negros_Intensos} />
        </group>
        <mesh geometry={nodes.BezierCurve_0.geometry} material={materials['Material.001']} position={[0.204, 1.263, 0.273]} rotation={[0, Math.PI / 2, 0]} scale={0.176} />
        <mesh geometry={nodes.BezierCurve001_0.geometry} material={materials.material} position={[0.217, 0.941, 0.63]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[-0.194, 0.194, 0.194]} />
        <mesh geometry={nodes.Cube_0.geometry} material={materials['Material.001']} position={[0.214, 3.133, 1.052]} scale={0.049} />
        <mesh geometry={nodes.BezierCurve002_0.geometry} material={materials.material} position={[0.214, 1.742, 2.749]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.189, 0.336, 0.189]} />
        <mesh geometry={nodes.Cube002_0.geometry} material={materials.Root} position={[0.21, 1.266, 0.051]} scale={0.021} />
        <mesh geometry={nodes.Cube003_0.geometry} material={materials.Root} position={[0.209, 1.266, 0.048]} rotation={[0, 0, -1.566]} scale={0.021} />
        <mesh geometry={nodes.Cylinder_0.geometry} material={materials.Root} position={[0.219, 1.269, 0.497]} rotation={[1.561, 0, 0]} scale={[0.029, 0.029, 0.263]} />
        <mesh geometry={nodes.BezierCurve003_0.geometry} material={materials.material} position={[0.214, 1.417, 1.606]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.161, 0.286, 0.161]} />
        <mesh geometry={nodes.BezierCurve004_0.geometry} material={materials.material} position={[0.214, 4.071, 1.578]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.161, 0.286, 0.161]} />
        <mesh geometry={nodes.Cylinder001_0.geometry} material={materials.Root} position={[0.219, 4.227, 0.501]} rotation={[1.561, 0, 0]} scale={[0.029, 0.029, 0.263]} />
        <mesh geometry={nodes.Cube004_0.geometry} material={materials.Root} position={[0.209, 4.215, 0.059]} rotation={[0, 0, -1.566]} scale={0.021} />
        <mesh geometry={nodes.Cube005_0.geometry} material={materials.Root} position={[0.21, 4.215, 0.062]} scale={0.021} />
        <mesh geometry={nodes.BezierCurve005_0.geometry} material={materials.material} position={[0.214, 3.891, 2.721]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.189, 0.336, 0.189]} />
        <mesh geometry={nodes.Cube006_0.geometry} material={materials['Material.001']} position={[0.214, 5.283, 1.024]} scale={0.049} />
        <mesh geometry={nodes.BezierCurve006_0.geometry} material={materials.material} position={[0.217, 3.899, 0.634]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[-0.194, 0.194, 0.194]} />
        <mesh geometry={nodes.BezierCurve007_0.geometry} material={materials['Material.001']} position={[0.204, 4.222, 0.277]} rotation={[0, Math.PI / 2, 0]} scale={0.176} />
        <mesh geometry={nodes.BezierCurve008_0.geometry} material={materials.material} position={[-0.578, 1.249, 1.595]} rotation={[-1.971, 0, Math.PI / 2]} scale={[0.161, 0.286, 0.161]} />
        <mesh geometry={nodes.Cylinder002_0.geometry} material={materials.Root} position={[-0.573, 1.978, 0.794]} rotation={[2.431, 0, 0]} scale={[0.029, 0.029, 0.263]} />
        <mesh geometry={nodes.Cube007_0.geometry} material={materials.Root} position={[-0.583, 2.319, 0.502]} rotation={[0.871, 0, -1.566]} scale={0.021} />
        <mesh geometry={nodes.Cube008_0.geometry} material={materials.Root} position={[-0.582, 2.317, 0.504]} rotation={[0.871, 0, 0]} scale={0.021} />
        <mesh geometry={nodes.BezierCurve009_0.geometry} material={materials.material} position={[-0.578, 1.742, 2.712]} rotation={[-2.515, 0, Math.PI / 2]} scale={[0.189, 0.336, 0.189]} />
        <mesh geometry={nodes.Cube009_0.geometry} material={materials['Material.001']} position={[-0.578, 3.133, 1.015]} scale={0.049} />
        <mesh geometry={nodes.BezierCurve010_0.geometry} material={materials.material} position={[-0.575, 1.665, 0.628]} rotation={[-2.271, -Math.PI / 2, 0]} scale={[-0.194, 0.194, 0.194]} />
        <mesh geometry={nodes.BezierCurve011_0.geometry} material={materials['Material.001']} position={[-0.588, 2.146, 0.645]} rotation={[0.871, Math.PI / 2, 0]} scale={0.176} />
        <mesh geometry={nodes.BezierCurve012_0.geometry} material={materials['Material.001']} position={[-0.597, 3.147, 0.277]} rotation={[0, Math.PI / 2, 0]} scale={0.176} />
        <mesh geometry={nodes.BezierCurve013_0.geometry} material={materials.material} position={[-0.585, 2.824, 0.634]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[-0.194, 0.194, 0.194]} />
        <mesh geometry={nodes.Cube010_0.geometry} material={materials['Material.001']} position={[-0.588, 4.208, 1.024]} scale={0.049} />
        <mesh geometry={nodes.BezierCurve014_0.geometry} material={materials.material} position={[-0.588, 3.891, 2.74]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.189, 0.336, 0.189]} />
        <mesh geometry={nodes.Cube011_0.geometry} material={materials.Root} position={[-0.592, 3.14, 0.062]} scale={0.021} />
        <mesh geometry={nodes.Cube012_0.geometry} material={materials.Root} position={[-0.592, 3.141, 0.059]} rotation={[0, 0, -1.566]} scale={0.021} />
        <mesh geometry={nodes.Cylinder003_0.geometry} material={materials.Root} position={[-0.582, 3.152, 0.501]} rotation={[1.561, 0, 0]} scale={[0.029, 0.029, 0.263]} />
        <mesh geometry={nodes.BezierCurve015_0.geometry} material={materials.material} position={[-0.588, 3.294, 1.584]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.161, 0.286, 0.161]} />
        <mesh geometry={nodes.Cube013_0.geometry} material={materials.Cuello} position={[-0.194, 1.009, 3.409]} rotation={[-Math.PI, 0, 0]} scale={[-0.228, 0.383, 0.27]} />
        <mesh geometry={nodes.BezierCurve017_0.geometry} material={materials.Root} position={[0.214, 2.648, 2.831]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.122, 0.217, 0.122]} />
        <mesh geometry={nodes.BezierCurve018_0.geometry} material={materials.material} position={[-0.211, 1.766, 2.811]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.208, 0.369, 0.208]} />
        <mesh geometry={nodes.BezierCurve016_0.geometry} material={materials.material} position={[-0.211, 3.906, 2.778]} rotation={[-1.79, 0, -Math.PI / 2]} scale={[0.208, 0.369, 0.208]} />
        <mesh geometry={nodes.BezierCurve019_0.geometry} material={materials.Root} position={[0.214, 3.146, 2.835]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.122, 0.217, 0.122]} />
        <mesh geometry={nodes.BezierCurve020_0.geometry} material={materials.Root} position={[-0.61, 3.149, 2.836]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.122, 0.217, 0.122]} />
        <mesh geometry={nodes.BezierCurve021_0.geometry} material={materials.Root} position={[-0.61, 2.651, 2.832]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.122, 0.217, 0.122]} />
        <mesh geometry={nodes.BezierCurve023_0.geometry} material={materials.Cuello} position={[0.012, -0.381, 3.02]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.064} />
        <mesh geometry={nodes.BezierCurve024_0.geometry} material={materials.Cuello} position={[-0.401, -0.381, 3.015]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.064} />
        <mesh geometry={nodes.BezierCurve025_0.geometry} material={materials.Root} position={[0.008, 0.243, 2.983]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.064, 0.254, 0.064]} />
        <mesh geometry={nodes.BezierCurve026_0.geometry} material={materials.Root} position={[-0.415, 0.243, 2.983]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.064, 0.254, 0.064]} />
        <mesh geometry={nodes.Sphere_0.geometry} material={materials.material} position={[0.108, -0.034, 3.289]} rotation={[-0.972, -0.218, 1.12]} scale={[0.212, 0.158, 0.221]} />
        <mesh geometry={nodes.Sphere001_0.geometry} material={materials.material} position={[-0.515, -0.038, 3.288]} rotation={[-0.946, 0.108, 1.576]} scale={[0.212, 0.158, 0.221]} />
        <mesh geometry={nodes.BezierCurve027_0.geometry} material={materials.Cuello} position={[0.271, -0.206, 3.183]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.366} />
        <mesh geometry={nodes.BezierCurve028_0.geometry} material={materials.Cuello} position={[-0.655, -0.206, 3.183]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.366} />
        <mesh geometry={nodes.Cube014_0.geometry} material={materials.Root} position={[0.172, -0.033, 3.187]} scale={[0.027, 0.051, 0.027]} />
        <mesh geometry={nodes.Cube015_0.geometry} material={materials.Root} position={[-0.832, -0.047, 3.189]} scale={[0.027, 0.051, 0.027]} />
        <mesh geometry={nodes.BezierCurve087_0.geometry} material={materials.Root} position={[-5.609, -7.123, 0.899]} rotation={[Math.PI / 2, 1.217, -Math.PI / 2]} scale={0.297} />
        <mesh geometry={nodes.BezierCurve088_0.geometry} material={materials.Root} position={[-5.513, -6.827, 0.929]} rotation={[1.571, 1.217, -3.118]} scale={0.1} />
        <mesh geometry={nodes.BezierCurve089_0.geometry} material={materials.Root} position={[4.592, -6.877, 0.725]} rotation={[-1.571, 1.151, 0.024]} scale={0.1} />
        <mesh geometry={nodes.BezierCurve090_0.geometry} material={materials.Root} position={[4.73, -7.156, 0.695]} rotation={[-Math.PI / 2, 1.151, Math.PI / 2]} scale={0.297} />
        <mesh geometry={nodes.Cube049_0.geometry} material={materials.Root} position={[-4.276, 1.912, 3.189]} scale={[0.027, 0.051, 0.027]} />
        <mesh geometry={nodes.Cube053_0.geometry} material={materials.Root} position={[-3.272, 1.926, 3.187]} scale={[0.027, 0.051, 0.027]} />
        <mesh geometry={nodes.BezierCurve100_0.geometry} material={materials.Cuello} position={[-4.099, 1.752, 3.183]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.366} />
        <mesh geometry={nodes.BezierCurve101_0.geometry} material={materials.Cuello} position={[-3.173, 1.752, 3.183]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.366} />
        <mesh geometry={nodes.Sphere006_0.geometry} material={materials.material} position={[-3.959, 1.921, 3.288]} rotation={[-0.946, 0.108, 1.576]} scale={[0.212, 0.158, 0.221]} />
        <mesh geometry={nodes.Sphere010_0.geometry} material={materials.material} position={[-3.336, 1.924, 3.289]} rotation={[-0.972, -0.218, 1.12]} scale={[0.212, 0.158, 0.221]} />
        <mesh geometry={nodes.BezierCurve102_0.geometry} material={materials.Root} position={[-3.859, 2.201, 2.983]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.064, 0.254, 0.064]} />
        <mesh geometry={nodes.BezierCurve103_0.geometry} material={materials.Root} position={[-3.436, 2.201, 2.983]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.064, 0.254, 0.064]} />
        <mesh geometry={nodes.BezierCurve104_0.geometry} material={materials.Cuello} position={[-3.846, 1.577, 3.015]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.064} />
        <mesh geometry={nodes.BezierCurve105_0.geometry} material={materials.Cuello} position={[-3.432, 1.577, 3.02]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.064} />
        <mesh geometry={nodes.BezierCurve106_0.geometry} material={materials.Cuello} position={[-3.638, 5.13, 2.818]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.105} />
        <mesh geometry={nodes.BezierCurve107_0.geometry} material={materials.Root} position={[-4.055, 4.61, 2.832]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.122, 0.217, 0.122]} />
        <mesh geometry={nodes.BezierCurve108_0.geometry} material={materials.Root} position={[-4.055, 5.108, 2.836]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.122, 0.217, 0.122]} />
        <mesh geometry={nodes.BezierCurve109_0.geometry} material={materials.Root} position={[-3.23, 5.105, 2.835]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.122, 0.217, 0.122]} />
        <mesh geometry={nodes.BezierCurve110_0.geometry} material={materials.material} position={[-3.655, 5.864, 2.778]} rotation={[-1.79, 0, -Math.PI / 2]} scale={[0.208, 0.369, 0.208]} />
        <mesh geometry={nodes.BezierCurve111_0.geometry} material={materials.material} position={[-3.655, 3.724, 2.811]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.208, 0.369, 0.208]} />
        <mesh geometry={nodes.BezierCurve112_0.geometry} material={materials.Root} position={[-3.23, 4.607, 2.831]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.122, 0.217, 0.122]} />
        <mesh geometry={nodes.Cube054_0.geometry} material={materials.Cuello} position={[-3.639, 2.967, 3.409]} rotation={[-Math.PI, 0, 0]} scale={[-0.228, 0.383, 0.27]} />
        <mesh geometry={nodes.BezierCurve113_0.geometry} material={materials.material} position={[-4.032, 5.253, 1.584]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.161, 0.286, 0.161]} />
        <mesh geometry={nodes.Cylinder012_0.geometry} material={materials.Root} position={[-4.027, 5.111, 0.501]} rotation={[1.561, 0, 0]} scale={[0.029, 0.029, 0.263]} />
        <mesh geometry={nodes.Cube055_0.geometry} material={materials.Root} position={[-4.037, 5.099, 0.059]} rotation={[0, 0, -1.566]} scale={0.021} />
        <mesh geometry={nodes.Cube056_0.geometry} material={materials.Root} position={[-4.036, 5.099, 0.062]} scale={0.021} />
        <mesh geometry={nodes.BezierCurve114_0.geometry} material={materials.material} position={[-4.032, 5.85, 2.74]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.189, 0.336, 0.189]} />
        <mesh geometry={nodes.Cube057_0.geometry} material={materials['Material.001']} position={[-4.032, 6.167, 1.024]} scale={0.049} />
        <mesh geometry={nodes.BezierCurve115_0.geometry} material={materials.material} position={[-4.029, 4.783, 0.634]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[-0.194, 0.194, 0.194]} />
        <mesh geometry={nodes.BezierCurve116_0.geometry} material={materials['Material.001']} position={[-4.042, 5.106, 0.277]} rotation={[0, Math.PI / 2, 0]} scale={0.176} />
        <mesh geometry={nodes.BezierCurve117_0.geometry} material={materials['Material.001']} position={[-4.033, 4.104, 0.645]} rotation={[0.871, Math.PI / 2, 0]} scale={0.176} />
        <mesh geometry={nodes.BezierCurve118_0.geometry} material={materials.material} position={[-4.02, 3.623, 0.628]} rotation={[-2.271, -Math.PI / 2, 0]} scale={[-0.194, 0.194, 0.194]} />
        <mesh geometry={nodes.Cube058_0.geometry} material={materials['Material.001']} position={[-4.023, 5.092, 1.015]} scale={0.049} />
        <mesh geometry={nodes.BezierCurve119_0.geometry} material={materials.material} position={[-4.023, 3.7, 2.712]} rotation={[-2.515, 0, Math.PI / 2]} scale={[0.189, 0.336, 0.189]} />
        <mesh geometry={nodes.Cube059_0.geometry} material={materials.Root} position={[-4.027, 4.276, 0.504]} rotation={[0.871, 0, 0]} scale={0.021} />
        <mesh geometry={nodes.Cube060_0.geometry} material={materials.Root} position={[-4.028, 4.278, 0.502]} rotation={[0.871, 0, -1.566]} scale={0.021} />
        <mesh geometry={nodes.Cylinder013_0.geometry} material={materials.Root} position={[-4.017, 3.936, 0.794]} rotation={[2.431, 0, 0]} scale={[0.029, 0.029, 0.263]} />
        <mesh geometry={nodes.BezierCurve120_0.geometry} material={materials.material} position={[-4.023, 3.208, 1.595]} rotation={[-1.971, 0, Math.PI / 2]} scale={[0.161, 0.286, 0.161]} />
        <mesh geometry={nodes.BezierCurve121_0.geometry} material={materials['Material.001']} position={[-3.24, 6.18, 0.277]} rotation={[0, Math.PI / 2, 0]} scale={0.176} />
        <mesh geometry={nodes.BezierCurve122_0.geometry} material={materials.material} position={[-3.227, 5.858, 0.634]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[-0.194, 0.194, 0.194]} />
        <mesh geometry={nodes.Cube061_0.geometry} material={materials['Material.001']} position={[-3.23, 7.241, 1.024]} scale={0.049} />
        <mesh geometry={nodes.BezierCurve022_0.geometry} material={materials.Cuello} position={[-0.194, 3.172, 2.818]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.105} />
        <mesh geometry={nodes.BezierCurve123_0.geometry} material={materials.material} position={[-3.23, 5.85, 2.721]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.189, 0.336, 0.189]} />
        <mesh geometry={nodes.Cube062_0.geometry} material={materials.Root} position={[-3.235, 6.174, 0.062]} scale={0.021} />
        <mesh geometry={nodes.Cube063_0.geometry} material={materials.Root} position={[-3.235, 6.174, 0.059]} rotation={[0, 0, -1.566]} scale={0.021} />
        <mesh geometry={nodes.Cylinder014_0.geometry} material={materials.Root} position={[-3.225, 6.186, 0.501]} rotation={[1.561, 0, 0]} scale={[0.029, 0.029, 0.263]} />
        <mesh geometry={nodes.BezierCurve124_0.geometry} material={materials.material} position={[-3.23, 6.03, 1.578]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.161, 0.286, 0.161]} />
        <mesh geometry={nodes.BezierCurve125_0.geometry} material={materials.material} position={[-3.23, 3.375, 1.606]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.161, 0.286, 0.161]} />
        <mesh geometry={nodes.Cylinder015_0.geometry} material={materials.Root} position={[-3.225, 3.227, 0.497]} rotation={[1.561, 0, 0]} scale={[0.029, 0.029, 0.263]} />
        <mesh geometry={nodes.Cube064_0.geometry} material={materials.Root} position={[-3.235, 3.225, 0.048]} rotation={[0, 0, -1.566]} scale={0.021} />
        <mesh geometry={nodes.Cube065_0.geometry} material={materials.Root} position={[-3.235, 3.224, 0.051]} scale={0.021} />
        <mesh geometry={nodes.BezierCurve126_0.geometry} material={materials.material} position={[-3.23, 3.7, 2.749]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.189, 0.336, 0.189]} />
        <mesh geometry={nodes.Cube066_0.geometry} material={materials['Material.001']} position={[-3.23, 5.092, 1.052]} scale={0.049} />
        <mesh geometry={nodes.BezierCurve127_0.geometry} material={materials.material} position={[-3.227, 2.899, 0.63]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[-0.194, 0.194, 0.194]} />
        <mesh geometry={nodes.BezierCurve128_0.geometry} material={materials['Material.001']} position={[-3.24, 3.222, 0.273]} rotation={[0, Math.PI / 2, 0]} scale={0.176} />
        <mesh geometry={nodes.BezierCurve129_0.geometry} material={materials['Material.001']} position={[3.295, 6.577, 0.273]} rotation={[0, Math.PI / 2, 0]} scale={0.176} />
        <mesh geometry={nodes.BezierCurve130_0.geometry} material={materials.material} position={[3.308, 6.254, 0.63]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[-0.194, 0.194, 0.194]} />
        <mesh geometry={nodes.Cube069_0.geometry} material={materials['Material.001']} position={[3.305, 8.447, 1.052]} scale={0.049} />
        <mesh geometry={nodes.BezierCurve131_0.geometry} material={materials.material} position={[3.305, 7.056, 2.749]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.189, 0.336, 0.189]} />
        <mesh geometry={nodes.Cube070_0.geometry} material={materials.Root} position={[3.301, 6.58, 0.051]} scale={0.021} />
        <mesh geometry={nodes.Cube071_0.geometry} material={materials.Root} position={[3.3, 6.58, 0.048]} rotation={[0, 0, -1.566]} scale={0.021} />
        <mesh geometry={nodes.Cylinder016_0.geometry} material={materials.Root} position={[3.31, 6.582, 0.497]} rotation={[1.561, 0, 0]} scale={[0.029, 0.029, 0.263]} />
        <mesh geometry={nodes.BezierCurve132_0.geometry} material={materials.material} position={[3.305, 6.731, 1.606]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.161, 0.286, 0.161]} />
        <mesh geometry={nodes.BezierCurve133_0.geometry} material={materials.material} position={[3.305, 9.385, 1.578]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.161, 0.286, 0.161]} />
        <mesh geometry={nodes.Cylinder017_0.geometry} material={materials.Root} position={[3.31, 9.541, 0.501]} rotation={[1.561, 0, 0]} scale={[0.029, 0.029, 0.263]} />
        <mesh geometry={nodes.Cube072_0.geometry} material={materials.Root} position={[3.3, 9.529, 0.059]} rotation={[0, 0, -1.566]} scale={0.021} />
        <mesh geometry={nodes.Cube073_0.geometry} material={materials.Root} position={[3.301, 9.529, 0.062]} scale={0.021} />
        <mesh geometry={nodes.BezierCurve134_0.geometry} material={materials.material} position={[3.305, 9.205, 2.721]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.189, 0.336, 0.189]} />
        <mesh geometry={nodes.Cube074_0.geometry} material={materials['Material.001']} position={[3.305, 10.597, 1.024]} scale={0.049} />
        <mesh geometry={nodes.BezierCurve135_0.geometry} material={materials.material} position={[3.308, 9.213, 0.634]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[-0.194, 0.194, 0.194]} />
        <mesh geometry={nodes.BezierCurve136_0.geometry} material={materials['Material.001']} position={[3.295, 9.536, 0.277]} rotation={[0, Math.PI / 2, 0]} scale={0.176} />
        <mesh geometry={nodes.BezierCurve137_0.geometry} material={materials.material} position={[2.513, 6.563, 1.595]} rotation={[-1.971, 0, Math.PI / 2]} scale={[0.161, 0.286, 0.161]} />
        <mesh geometry={nodes.Cylinder018_0.geometry} material={materials.Root} position={[2.518, 7.292, 0.794]} rotation={[2.431, 0, 0]} scale={[0.029, 0.029, 0.263]} />
        <mesh geometry={nodes.Cube075_0.geometry} material={materials.Root} position={[2.508, 7.633, 0.502]} rotation={[0.871, 0, -1.566]} scale={0.021} />
        <mesh geometry={nodes.Cube076_0.geometry} material={materials.Root} position={[2.509, 7.631, 0.504]} rotation={[0.871, 0, 0]} scale={0.021} />
        <mesh geometry={nodes.BezierCurve138_0.geometry} material={materials.material} position={[2.513, 7.056, 2.712]} rotation={[-2.515, 0, Math.PI / 2]} scale={[0.189, 0.336, 0.189]} />
        <mesh geometry={nodes.Cube077_0.geometry} material={materials['Material.001']} position={[2.513, 8.447, 1.015]} scale={0.049} />
        <mesh geometry={nodes.BezierCurve139_0.geometry} material={materials.material} position={[2.516, 6.979, 0.628]} rotation={[-2.271, -Math.PI / 2, 0]} scale={[-0.194, 0.194, 0.194]} />
        <mesh geometry={nodes.BezierCurve140_0.geometry} material={materials['Material.001']} position={[2.503, 7.46, 0.645]} rotation={[0.871, Math.PI / 2, 0]} scale={0.176} />
        <mesh geometry={nodes.BezierCurve141_0.geometry} material={materials['Material.001']} position={[2.494, 8.461, 0.277]} rotation={[0, Math.PI / 2, 0]} scale={0.176} />
        <mesh geometry={nodes.BezierCurve142_0.geometry} material={materials.material} position={[2.507, 8.138, 0.634]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[-0.194, 0.194, 0.194]} />
        <mesh geometry={nodes.Cube078_0.geometry} material={materials['Material.001']} position={[2.504, 9.522, 1.024]} scale={0.049} />
        <mesh geometry={nodes.BezierCurve143_0.geometry} material={materials.material} position={[2.504, 9.205, 2.74]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.189, 0.336, 0.189]} />
        <mesh geometry={nodes.Cube079_0.geometry} material={materials.Root} position={[2.499, 8.454, 0.062]} scale={0.021} />
        <mesh geometry={nodes.Cube080_0.geometry} material={materials.Root} position={[2.499, 8.455, 0.059]} rotation={[0, 0, -1.566]} scale={0.021} />
        <mesh geometry={nodes.Cylinder019_0.geometry} material={materials.Root} position={[2.509, 8.466, 0.501]} rotation={[1.561, 0, 0]} scale={[0.029, 0.029, 0.263]} />
        <mesh geometry={nodes.BezierCurve144_0.geometry} material={materials.material} position={[2.504, 8.608, 1.584]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.161, 0.286, 0.161]} />
        <mesh geometry={nodes.Cube081_0.geometry} material={materials.Cuello} position={[2.897, 6.323, 3.409]} rotation={[-Math.PI, 0, 0]} scale={[-0.228, 0.383, 0.27]} />
        <mesh geometry={nodes.BezierCurve145_0.geometry} material={materials.Root} position={[3.305, 7.962, 2.831]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.122, 0.217, 0.122]} />
        <mesh geometry={nodes.BezierCurve146_0.geometry} material={materials.material} position={[2.88, 7.08, 2.811]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.208, 0.369, 0.208]} />
        <mesh geometry={nodes.BezierCurve147_0.geometry} material={materials.material} position={[2.88, 9.22, 2.778]} rotation={[-1.79, 0, -Math.PI / 2]} scale={[0.208, 0.369, 0.208]} />
        <mesh geometry={nodes.BezierCurve148_0.geometry} material={materials.Root} position={[3.305, 8.46, 2.835]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.122, 0.217, 0.122]} />
        <mesh geometry={nodes.BezierCurve149_0.geometry} material={materials.Root} position={[2.481, 8.463, 2.836]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.122, 0.217, 0.122]} />
        <mesh geometry={nodes.BezierCurve150_0.geometry} material={materials.Root} position={[2.481, 7.965, 2.832]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.122, 0.217, 0.122]} />
        <mesh geometry={nodes.BezierCurve151_0.geometry} material={materials.Cuello} position={[2.897, 8.486, 2.818]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.105} />
        <mesh geometry={nodes.BezierCurve152_0.geometry} material={materials.Cuello} position={[3.104, 4.933, 3.02]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.064} />
        <mesh geometry={nodes.BezierCurve153_0.geometry} material={materials.Cuello} position={[2.69, 4.933, 3.015]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.064} />
        <mesh geometry={nodes.BezierCurve154_0.geometry} material={materials.Root} position={[3.099, 5.557, 2.983]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.064, 0.254, 0.064]} />
        <mesh geometry={nodes.BezierCurve155_0.geometry} material={materials.Root} position={[2.677, 5.557, 2.983]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.064, 0.254, 0.064]} />
        <mesh geometry={nodes.Sphere011_0.geometry} material={materials.material} position={[3.199, 5.28, 3.289]} rotation={[-0.972, -0.218, 1.12]} scale={[0.212, 0.158, 0.221]} />
        <mesh geometry={nodes.Sphere012_0.geometry} material={materials.material} position={[2.576, 5.276, 3.288]} rotation={[-0.946, 0.108, 1.576]} scale={[0.212, 0.158, 0.221]} />
        <mesh geometry={nodes.BezierCurve156_0.geometry} material={materials.Cuello} position={[3.362, 5.108, 3.183]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.366} />
        <mesh geometry={nodes.BezierCurve157_0.geometry} material={materials.Cuello} position={[2.436, 5.108, 3.183]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.366} />
        <mesh geometry={nodes.Cube082_0.geometry} material={materials.Root} position={[3.263, 5.281, 3.187]} scale={[0.027, 0.051, 0.027]} />
        <mesh geometry={nodes.Cube083_0.geometry} material={materials.Root} position={[2.259, 5.267, 3.189]} scale={[0.027, 0.051, 0.027]} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/ep5/hoth/battle_of_hoth.glb')
