/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/models/darthVader/darth_vader.glb 
Author: shaunwho (https://sketchfab.com/shaunwho)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/darth-vader-helmet-6d4da7fbe3864661a1305c2feac01d8f
Title: Darth Vader Helmet
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'

export function DarthVader(props) {
  const { nodes, materials } = useGLTF('./models/ep6/darthVader/darth_vader.glb')
  const [modelLoaded, setModelLoaded] = useState(false);

  useEffect(() => {
    const timeoutId = setTimeout(() => {
      setModelLoaded(true);
    }, 70000);

    // Limpiar el temporizador si el componente se desmonta antes de que se cargue el modelo
    return () => clearTimeout(timeoutId);
  }, []); // El array vacío asegura que este efecto se ejecute solo una vez al montar el componente

  if (!modelLoaded) {
    return null; // O puedes devolver un indicador de carga aquí
  }
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.blinn2SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.blinn2SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.blinn2SG} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.blinn2SG} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.blinn2SG} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/ep6/darthVader/darth_vader.glb')
