/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/models/ep6/speeder/speeder.glb 
Author: keith_jones (https://sketchfab.com/keith_jones)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/speeder-7eea496dbc034eae9ae505f84c5a02a1
Title: Speeder
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'

export function Speeder(props) {
  const { nodes, materials } = useGLTF('./models/ep6/speeder/speeder.glb')
  const [modelLoaded, setModelLoaded] = useState(false);

  useEffect(() => {
    const timeoutId = setTimeout(() => {
      setModelLoaded(true);
    }, 70000);

    // Limpiar el temporizador si el componente se desmonta antes de que se cargue el modelo
    return () => clearTimeout(timeoutId);
  }, []); // El array vacío asegura que este efecto se ejecute solo una vez al montar el componente

  if (!modelLoaded) {
    return null; // O puedes devolver un indicador de carga aquí
  }
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.032, 0.039, -0.193]}>
            <mesh geometry={nodes.Object_5.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_7.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Object_9.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_11.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Object_13.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_15.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Object_17.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_19.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Object_21.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_23.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Object_25.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_27.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Object_29.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_31.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Object_33.geometry} material={materials['Default.002']} />
            <mesh geometry={nodes.Object_35.geometry} material={materials['Default.003']} />
            <mesh geometry={nodes.Object_37.geometry} material={materials['Default.003']} />
            <mesh geometry={nodes.Object_39.geometry} material={materials['Material.011']} />
            <mesh geometry={nodes.Object_41.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Object_43.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Object_45.geometry} material={materials.nobs} />
            <mesh geometry={nodes.Object_47.geometry} material={materials.nobs} />
            <mesh geometry={nodes.Object_49.geometry} material={materials.nobs} />
            <mesh geometry={nodes.Object_51.geometry} material={materials.nobs} />
            <mesh geometry={nodes.Object_53.geometry} material={materials.nobs} />
            <mesh geometry={nodes.Object_55.geometry} material={materials['Default.004']} />
            <mesh geometry={nodes.Object_57.geometry} material={materials['Default.003']} />
            <mesh geometry={nodes.Object_58.geometry} material={materials['Material.012']} />
            <mesh geometry={nodes.Object_60.geometry} material={materials['Material.012']} />
            <mesh geometry={nodes.Object_62.geometry} material={materials['Material.012']} />
            <mesh geometry={nodes.Object_64.geometry} material={materials['Default.001']} />
            <mesh geometry={nodes.Object_65.geometry} material={materials.Cyan} />
            <mesh geometry={nodes.Object_67.geometry} material={materials['Default.001']} />
            <mesh geometry={nodes.Object_68.geometry} material={materials.Cyan} />
            <mesh geometry={nodes.Object_70.geometry} material={materials['Default.001']} />
            <mesh geometry={nodes.Object_71.geometry} material={materials.cable} />
            <mesh geometry={nodes.Object_73.geometry} material={materials['Default.001']} />
            <mesh geometry={nodes.Object_74.geometry} material={materials.cable} />
            <mesh geometry={nodes.Object_76.geometry} material={materials.Default} />
            <mesh geometry={nodes.Object_78.geometry} material={materials['Material.016']} />
            <mesh geometry={nodes.Object_80.geometry} material={materials['Material.013']} />
            <mesh geometry={nodes.Object_82.geometry} material={materials['Material.006']} />
            <mesh geometry={nodes.Object_84.geometry} material={materials['Material.015']} />
            <mesh geometry={nodes.Object_86.geometry} material={materials['Material.005']} />
            <mesh geometry={nodes.Object_88.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Object_90.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Object_92.geometry} material={materials['Material.003']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/ep6/speeder/speeder.glb')
