/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/models/ep9/exegol/exegol_descent.glb 
Author: David Onizaki (https://sketchfab.com/donizaki)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/star-wars-exegol-descent-d6a186fbfb8f4841bcd7f29b68160610
Title: Star Wars: Exegol Descent
*/

import React, { useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Exegol(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "./models/ep9/exegol/exegol_descent.glb"
  );
  const { actions } = useAnimations(animations, group);
  const [modelLoaded, setModelLoaded] = useState(false);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="Elevator_1"
                position={[0.147, 48.037, -0.015]}
                rotation={[Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="Object_4"
                  geometry={nodes.Object_4.geometry}
                  material={materials.Mat_Elevator}
                />
              </group>
              <group
                name="Lightning_2"
                position={[4.344, -12.495, -53.824]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.289, 1, 1]}
              >
                <mesh
                  name="Object_6"
                  geometry={nodes.Object_6.geometry}
                  material={materials.Material_Lightning}
                />
              </group>
              <group
                name="Lightning001_3"
                position={[4.673, -12.495, -35.161]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.289, 1, 1]}
              >
                <mesh
                  name="Object_8"
                  geometry={nodes.Object_8.geometry}
                  material={materials.Material_Lightning}
                />
              </group>
              <group
                name="Lightning002_4"
                position={[0.352, -12.495, -11.511]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.289, 1, 1]}
              >
                <mesh
                  name="Object_10"
                  geometry={nodes.Object_10.geometry}
                  material={materials.Material_Lightning}
                />
              </group>
              <group
                name="Lightning003_5"
                position={[1.783, -12.495, 23.413]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.289, 1, 1]}
              >
                <mesh
                  name="Object_12"
                  geometry={nodes.Object_12.geometry}
                  material={materials.Material_Lightning}
                />
              </group>
              <group name="Scene_Base_168" position={[0, 0.085, 0]}>
                <group
                  name="Chain_6"
                  position={[23.643, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Object_16"
                    geometry={nodes.Object_16.geometry}
                    material={materials.Mat_Chain}
                  />
                </group>
                <group
                  name="Chain001_7"
                  position={[-45.512, 0, -24.187]}
                  rotation={[Math.PI / 2, 0, -Math.PI / 4]}
                >
                  <mesh
                    name="Object_18"
                    geometry={nodes.Object_18.geometry}
                    material={materials.Mat_Chain}
                  />
                </group>
                <group
                  name="Chain002_8"
                  position={[-30.42, 0, -40.213]}
                  rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                >
                  <mesh
                    name="Object_20"
                    geometry={nodes.Object_20.geometry}
                    material={materials.Mat_Chain}
                  />
                </group>
                <group
                  name="Chain003_9"
                  position={[8.361, 0, -44.705]}
                  rotation={[Math.PI / 2, 0, -2.356]}
                >
                  <mesh
                    name="Object_22"
                    geometry={nodes.Object_22.geometry}
                    material={materials.Mat_Chain}
                  />
                </group>
                <group
                  name="Chain004_10"
                  position={[40.147, 0, -58.616]}
                  rotation={[Math.PI / 2, 0, Math.PI]}
                >
                  <mesh
                    name="Object_24"
                    geometry={nodes.Object_24.geometry}
                    material={materials.Mat_Chain}
                  />
                </group>
                <group
                  name="Chain005_11"
                  position={[64.157, 0, -43.26]}
                  rotation={[Math.PI / 2, 0, 2.356]}
                >
                  <mesh
                    name="Object_26"
                    geometry={nodes.Object_26.geometry}
                    material={materials.Mat_Chain}
                  />
                </group>
                <group
                  name="Chain006_12"
                  position={[58.793, 0, -22.502]}
                  rotation={[Math.PI / 2, 0, Math.PI / 2]}
                >
                  <mesh
                    name="Object_28"
                    geometry={nodes.Object_28.geometry}
                    material={materials.Mat_Chain}
                  />
                </group>
                <group
                  name="Chain007_13"
                  position={[49.977, 0, 3.36]}
                  rotation={[Math.PI / 2, 0, Math.PI / 4]}
                >
                  <mesh
                    name="Object_30"
                    geometry={nodes.Object_30.geometry}
                    material={materials.Mat_Chain}
                  />
                </group>
                <group
                  name="Chain008_14"
                  position={[14.745, 0, 35.154]}
                  rotation={[Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Object_32"
                    geometry={nodes.Object_32.geometry}
                    material={materials.Mat_Chain}
                  />
                </group>
                <group
                  name="Chain009_15"
                  position={[-5.148, 0, 62.451]}
                  rotation={[Math.PI / 2, 0, -Math.PI / 4]}
                >
                  <mesh
                    name="Object_34"
                    geometry={nodes.Object_34.geometry}
                    material={materials.Mat_Chain}
                  />
                </group>
                <group
                  name="Chain010_16"
                  position={[36.997, 0, 63.858]}
                  rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                >
                  <mesh
                    name="Object_36"
                    geometry={nodes.Object_36.geometry}
                    material={materials.Mat_Chain}
                  />
                </group>
                <group
                  name="Chain011_17"
                  position={[-21.577, 0, 67.268]}
                  rotation={[Math.PI / 2, 0, -2.356]}
                >
                  <mesh
                    name="Object_38"
                    geometry={nodes.Object_38.geometry}
                    material={materials.Mat_Chain}
                  />
                </group>
                <group
                  name="Chain012_18"
                  position={[5.262, 0, 11.461]}
                  rotation={[Math.PI / 2, 0, Math.PI]}
                >
                  <mesh
                    name="Object_40"
                    geometry={nodes.Object_40.geometry}
                    material={materials.Mat_Chain}
                  />
                </group>
                <group
                  name="Chain013_19"
                  position={[-26.455, 0, 22.9]}
                  rotation={[Math.PI / 2, 0, 2.356]}
                >
                  <mesh
                    name="Object_42"
                    geometry={nodes.Object_42.geometry}
                    material={materials.Mat_Chain}
                  />
                </group>
                <group
                  name="Chain014_20"
                  position={[-29.645, 0, -6.424]}
                  rotation={[Math.PI / 2, 0, 1.571]}
                >
                  <mesh
                    name="Object_44"
                    geometry={nodes.Object_44.geometry}
                    material={materials.Mat_Chain}
                  />
                </group>
                <group
                  name="Chain015_21"
                  position={[-13.588, 0, -23.155]}
                  rotation={[Math.PI / 2, 0, Math.PI / 4]}
                >
                  <mesh
                    name="Object_46"
                    geometry={nodes.Object_46.geometry}
                    material={materials.Mat_Chain}
                  />
                </group>
                <group name="Floor_Fissure_22" rotation={[Math.PI / 2, 0, 0]}>
                  <mesh
                    name="Object_48"
                    geometry={nodes.Object_48.geometry}
                    material={materials.mat_floor_fissure}
                  />
                </group>
                <group name="Floor_Main_23" rotation={[Math.PI / 2, 0, 0]}>
                  <mesh
                    name="Object_50"
                    geometry={nodes.Object_50.geometry}
                    material={materials.Mat_Floor_Mega}
                  />
                </group>
                <group
                  name="Lightning_Rod001_25"
                  position={[5.102, 1.554, -35.769]}
                  rotation={[Math.PI / 2, 0, -1.041]}
                >
                  <mesh
                    name="Object_52"
                    geometry={nodes.Object_52.geometry}
                    material={materials.Mat_Lightning_Rod}
                  />
                </group>
                <group
                  name="Lightning_Rod002_26"
                  position={[3.608, 1.554, -54.438]}
                  rotation={[Math.PI / 2, 0, -2.361]}
                >
                  <mesh
                    name="Object_54"
                    geometry={nodes.Object_54.geometry}
                    material={materials.Mat_Lightning_Rod}
                  />
                </group>
                <group
                  name="Lightning_Rod003_27"
                  position={[-0.325, 1.554, -11.851]}
                  rotation={[Math.PI / 2, 0, -2.744]}
                >
                  <mesh
                    name="Object_56"
                    geometry={nodes.Object_56.geometry}
                    material={materials.Mat_Lightning_Rod}
                  />
                </group>
                <group
                  name="Lightning_Rod004_28"
                  position={[0.979, 1.554, 22.968]}
                  rotation={[Math.PI / 2, 0, -2.744]}
                >
                  <mesh
                    name="Object_58"
                    geometry={nodes.Object_58.geometry}
                    material={materials.Mat_Lightning_Rod}
                  />
                </group>
                <group name="Roof_29" rotation={[Math.PI / 2, 0, 0]}>
                  <mesh
                    name="Object_60"
                    geometry={nodes.Object_60.geometry}
                    material={materials.mat_wall_rock}
                  />
                </group>
                <group
                  name="Statue_1002_30"
                  position={[-40.207, -0.72, -44.115]}
                  rotation={[Math.PI / 2, 0, Math.PI / 2]}
                >
                  <mesh
                    name="Object_62"
                    geometry={nodes.Object_62.geometry}
                    material={materials.Material_Statue_1}
                  />
                  <mesh
                    name="Object_63"
                    geometry={nodes.Object_63.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_1009_31"
                  position={[-43.408, -1.113, 66.452]}
                  rotation={[Math.PI / 2, 0, Math.PI]}
                >
                  <mesh
                    name="Object_65"
                    geometry={nodes.Object_65.geometry}
                    material={materials.Material_Statue_1}
                  />
                  <mesh
                    name="Object_66"
                    geometry={nodes.Object_66.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_1011_32"
                  position={[5.328, 0, -68.444]}
                  rotation={[Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Object_68"
                    geometry={nodes.Object_68.geometry}
                    material={materials.Material_Statue_1}
                  />
                  <mesh
                    name="Object_69"
                    geometry={nodes.Object_69.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_1014_33"
                  position={[12.732, -1.113, -16.472]}
                  rotation={[Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Object_71"
                    geometry={nodes.Object_71.geometry}
                    material={materials.Material_Statue_1}
                  />
                  <mesh
                    name="Object_72"
                    geometry={nodes.Object_72.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_1017_34"
                  position={[-18.823, -1.113, 22.404]}
                  rotation={[Math.PI / 2, 0, Math.PI / 2]}
                >
                  <mesh
                    name="Object_74"
                    geometry={nodes.Object_74.geometry}
                    material={materials.Material_Statue_1}
                  />
                  <mesh
                    name="Object_75"
                    geometry={nodes.Object_75.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_1021_35"
                  position={[49.861, 0, -68.444]}
                  rotation={[Math.PI / 2, 0, Math.PI / 2]}
                >
                  <mesh
                    name="Object_77"
                    geometry={nodes.Object_77.geometry}
                    material={materials.Material_Statue_1}
                  />
                  <mesh
                    name="Object_78"
                    geometry={nodes.Object_78.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_1022_36"
                  position={[71.485, -0.72, -44.115]}
                  rotation={[Math.PI / 2, 0, Math.PI]}
                >
                  <mesh
                    name="Object_80"
                    geometry={nodes.Object_80.geometry}
                    material={materials.Material_Statue_1}
                  />
                  <mesh
                    name="Object_81"
                    geometry={nodes.Object_81.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_1024_37"
                  position={[49.248, -1.113, -21.52]}
                  rotation={[Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Object_83"
                    geometry={nodes.Object_83.geometry}
                    material={materials.Material_Statue_1}
                  />
                  <mesh
                    name="Object_84"
                    geometry={nodes.Object_84.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_1025_38"
                  position={[49.052, -1.113, 1.67]}
                  rotation={[Math.PI / 2, 0, Math.PI / 2]}
                >
                  <mesh
                    name="Object_86"
                    geometry={nodes.Object_86.geometry}
                    material={materials.Material_Statue_1}
                  />
                  <mesh
                    name="Object_87"
                    geometry={nodes.Object_87.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_1027_39"
                  position={[24.913, -1.113, 22.404]}
                  rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                >
                  <mesh
                    name="Object_89"
                    geometry={nodes.Object_89.geometry}
                    material={materials.Material_Statue_1}
                  />
                  <mesh
                    name="Object_90"
                    geometry={nodes.Object_90.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_2003_40"
                  position={[-40.78, 0, -21.355]}
                  rotation={[Math.PI / 2, 0, Math.PI / 2]}
                >
                  <mesh
                    name="Object_92"
                    geometry={nodes.Object_92.geometry}
                    material={materials.Material_Statue_2}
                  />
                  <mesh
                    name="Object_93"
                    geometry={nodes.Object_93.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_2004_41"
                  position={[-63.966, 0, 1.482]}
                  rotation={[Math.PI / 2, 0, Math.PI]}
                >
                  <mesh
                    name="Object_95"
                    geometry={nodes.Object_95.geometry}
                    material={materials.Material_Statue_2}
                  />
                  <mesh
                    name="Object_96"
                    geometry={nodes.Object_96.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_2006_42"
                  position={[-42.435, 0, 23.199]}
                  rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                >
                  <mesh
                    name="Object_98"
                    geometry={nodes.Object_98.geometry}
                    material={materials.Material_Statue_2}
                  />
                  <mesh
                    name="Object_99"
                    geometry={nodes.Object_99.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_2007_43"
                  position={[-66.204, -0.886, 45.893]}
                  rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                >
                  <mesh
                    name="Object_101"
                    geometry={nodes.Object_101.geometry}
                    material={materials.Material_Statue_2}
                  />
                  <mesh
                    name="Object_102"
                    geometry={nodes.Object_102.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_2012_44"
                  position={[-22.173, 0, -44.796]}
                  rotation={[Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Object_104"
                    geometry={nodes.Object_104.geometry}
                    material={materials.Material_Statue_2}
                  />
                  <mesh
                    name="Object_105"
                    geometry={nodes.Object_105.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_2015_45"
                  position={[-17.072, 0, 1.482]}
                  rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                >
                  <mesh
                    name="Object_107"
                    geometry={nodes.Object_107.geometry}
                    material={materials.Material_Statue_2}
                  />
                  <mesh
                    name="Object_108"
                    geometry={nodes.Object_108.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_2018_46"
                  position={[-19.31, -0.886, 45.893]}
                  rotation={[Math.PI / 2, 0, Math.PI]}
                >
                  <mesh
                    name="Object_110"
                    geometry={nodes.Object_110.geometry}
                    material={materials.Material_Statue_2}
                  />
                  <mesh
                    name="Object_111"
                    geometry={nodes.Object_111.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_2019_47"
                  position={[10.145, -0.886, 66.203]}
                  rotation={[Math.PI / 2, 0, Math.PI / 2]}
                >
                  <mesh
                    name="Object_113"
                    geometry={nodes.Object_113.geometry}
                    material={materials.Material_Statue_2}
                  />
                  <mesh
                    name="Object_114"
                    geometry={nodes.Object_114.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_2025_48"
                  position={[70.912, 0, -21.355]}
                  rotation={[Math.PI / 2, 0, Math.PI]}
                >
                  <mesh
                    name="Object_116"
                    geometry={nodes.Object_116.geometry}
                    material={materials.Material_Statue_2}
                  />
                  <mesh
                    name="Object_117"
                    geometry={nodes.Object_117.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_2029_49"
                  position={[24.426, -0.886, 45.893]}
                  rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                >
                  <mesh
                    name="Object_119"
                    geometry={nodes.Object_119.geometry}
                    material={materials.Material_Statue_2}
                  />
                  <mesh
                    name="Object_120"
                    geometry={nodes.Object_120.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_2030_50"
                  position={[46.487, -0.886, 66.203]}
                  rotation={[Math.PI / 2, 0, Math.PI]}
                >
                  <mesh
                    name="Object_122"
                    geometry={nodes.Object_122.geometry}
                    material={materials.Material_Statue_2}
                  />
                  <mesh
                    name="Object_123"
                    geometry={nodes.Object_123.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_3_51"
                  position={[-64.692, 0, -68.136]}
                  rotation={[Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Object_125"
                    geometry={nodes.Object_125.geometry}
                    material={materials.Material_Statue_3}
                  />
                  <mesh
                    name="Object_126"
                    geometry={nodes.Object_126.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_3007_52"
                  position={[-43.078, -0.688, 46.335]}
                  rotation={[Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Object_128"
                    geometry={nodes.Object_128.geometry}
                    material={materials.Material_Statue_3}
                  />
                  <mesh
                    name="Object_129"
                    geometry={nodes.Object_129.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_3008_53"
                  position={[-66.304, -0.688, 66.014]}
                  rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                >
                  <mesh
                    name="Object_131"
                    geometry={nodes.Object_131.geometry}
                    material={materials.Material_Statue_3}
                  />
                  <mesh
                    name="Object_132"
                    geometry={nodes.Object_132.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_3009_54"
                  position={[-17.798, 0, -68.136]}
                  rotation={[Math.PI / 2, 0, Math.PI / 2]}
                >
                  <mesh
                    name="Object_134"
                    geometry={nodes.Object_134.geometry}
                    material={materials.Material_Statue_3}
                  />
                  <mesh
                    name="Object_135"
                    geometry={nodes.Object_135.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_3010_55"
                  position={[-4.498, 0, -44.45]}
                  rotation={[Math.PI / 2, 0, Math.PI]}
                >
                  <mesh
                    name="Object_137"
                    geometry={nodes.Object_137.geometry}
                    material={materials.Material_Statue_3}
                  />
                  <mesh
                    name="Object_138"
                    geometry={nodes.Object_138.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_3012_56"
                  position={[-17.251, -0.688, -21.347]}
                  rotation={[Math.PI / 2, 0, Math.PI]}
                >
                  <mesh
                    name="Object_140"
                    geometry={nodes.Object_140.geometry}
                    material={materials.Material_Statue_3}
                  />
                  <mesh
                    name="Object_141"
                    geometry={nodes.Object_141.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_3015_57"
                  position={[10.877, -0.688, 22.994]}
                  rotation={[Math.PI / 2, 0, Math.PI]}
                >
                  <mesh
                    name="Object_143"
                    geometry={nodes.Object_143.geometry}
                    material={materials.Material_Statue_3}
                  />
                  <mesh
                    name="Object_144"
                    geometry={nodes.Object_144.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_3017_58"
                  position={[-11.699, -0.688, 66.014]}
                  rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                >
                  <mesh
                    name="Object_146"
                    geometry={nodes.Object_146.geometry}
                    material={materials.Material_Statue_3}
                  />
                  <mesh
                    name="Object_147"
                    geometry={nodes.Object_147.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_3018_59"
                  position={[25.938, 0, -68.136]}
                  rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                >
                  <mesh
                    name="Object_149"
                    geometry={nodes.Object_149.geometry}
                    material={materials.Material_Statue_3}
                  />
                  <mesh
                    name="Object_150"
                    geometry={nodes.Object_150.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_3019_60"
                  position={[49.545, 0, -44.45]}
                  rotation={[Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Object_152"
                    geometry={nodes.Object_152.geometry}
                    material={materials.Material_Statue_3}
                  />
                  <mesh
                    name="Object_153"
                    geometry={nodes.Object_153.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_3021_61"
                  position={[26.485, -0.688, -21.347]}
                  rotation={[Math.PI / 2, 0, Math.PI / 2]}
                >
                  <mesh
                    name="Object_155"
                    geometry={nodes.Object_155.geometry}
                    material={materials.Material_Statue_3}
                  />
                  <mesh
                    name="Object_156"
                    geometry={nodes.Object_156.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_3024_62"
                  position={[47.564, -0.688, 23.127]}
                  rotation={[Math.PI / 2, 0, Math.PI / 2]}
                >
                  <mesh
                    name="Object_158"
                    geometry={nodes.Object_158.geometry}
                    material={materials.Material_Statue_3}
                  />
                  <mesh
                    name="Object_159"
                    geometry={nodes.Object_159.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_3025_63"
                  position={[68.614, -0.688, 46.335]}
                  rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                >
                  <mesh
                    name="Object_161"
                    geometry={nodes.Object_161.geometry}
                    material={materials.Material_Statue_3}
                  />
                  <mesh
                    name="Object_162"
                    geometry={nodes.Object_162.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_Dest_Arm_1_64"
                  position={[-69.564, -4.202, -15.535]}
                  rotation={[0.625, -1.369, -0.228]}
                >
                  <mesh
                    name="Object_164"
                    geometry={nodes.Object_164.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Arm_1001_65"
                  position={[-34.593, -4.297, -38.922]}
                  rotation={[2.897, -1.066, 2.084]}
                >
                  <mesh
                    name="Object_166"
                    geometry={nodes.Object_166.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Arm_1002_66"
                  position={[-35.183, -4.056, -60.937]}
                  rotation={[3.019, -0.285, 2.264]}
                >
                  <mesh
                    name="Object_168"
                    geometry={nodes.Object_168.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Arm_1003_67"
                  position={[42.679, -4.056, -44.655]}
                  rotation={[2.978, 0.767, 2.413]}
                >
                  <mesh
                    name="Object_170"
                    geometry={nodes.Object_170.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Arm_1004_68"
                  position={[73.165, -4.056, -57.363]}
                  rotation={[2.96, -0.868, 2.159]}
                >
                  <mesh
                    name="Object_172"
                    geometry={nodes.Object_172.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Arm_1005_69"
                  position={[47.965, -4.056, -14.737]}
                  rotation={[2.96, -0.868, 2.159]}
                >
                  <mesh
                    name="Object_174"
                    geometry={nodes.Object_174.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Arm_1006_70"
                  position={[9.06, -4.056, 7.136]}
                  rotation={[1.937, -1.445, 1.096]}
                >
                  <mesh
                    name="Object_176"
                    geometry={nodes.Object_176.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Arm_1007_71"
                  position={[-67.702, -4.056, 28.595]}
                  rotation={[1.937, -1.445, 1.096]}
                >
                  <mesh
                    name="Object_178"
                    geometry={nodes.Object_178.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Arm_1008_72"
                  position={[-25.681, -4.056, 28.817]}
                  rotation={[3.004, 0.545, 2.37]}
                >
                  <mesh
                    name="Object_180"
                    geometry={nodes.Object_180.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Arm_1009_73"
                  position={[39.057, -4.056, 56.891]}
                  rotation={[3.004, 0.545, 2.37]}
                >
                  <mesh
                    name="Object_182"
                    geometry={nodes.Object_182.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Arm_1010_74"
                  position={[61.035, -4.056, 49.223]}
                  rotation={[3.024, -0.08, 2.289]}
                >
                  <mesh
                    name="Object_184"
                    geometry={nodes.Object_184.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Arm_1011_75"
                  position={[63.037, -4.056, 22.439]}
                  rotation={[3.009, 0.482, 2.36]}
                >
                  <mesh
                    name="Object_186"
                    geometry={nodes.Object_186.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Arm_2_76"
                  position={[-35.026, -1.566, -8.107]}
                  rotation={[0.011, -0.928, 1.21]}
                >
                  <mesh
                    name="Object_188"
                    geometry={nodes.Object_188.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Arm_2001_77"
                  position={[-52.129, -1.566, -23.83]}
                  rotation={[0.007, -0.287, 1.203]}
                >
                  <mesh
                    name="Object_190"
                    geometry={nodes.Object_190.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Arm_2002_78"
                  position={[-24.943, -1.566, -55.871]}
                  rotation={[3.115, -1.327, -1.967]}
                >
                  <mesh
                    name="Object_192"
                    geometry={nodes.Object_192.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Arm_2003_79"
                  position={[51.772, -1.566, -30.988]}
                  rotation={[3.115, -1.327, -1.967]}
                >
                  <mesh
                    name="Object_194"
                    geometry={nodes.Object_194.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Arm_2004_80"
                  position={[36.102, -1.566, -54.718]}
                  rotation={[3.132, -0.804, -1.947]}
                >
                  <mesh
                    name="Object_196"
                    geometry={nodes.Object_196.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Arm_2005_81"
                  position={[31.613, -1.566, -4.876]}
                  rotation={[3.135, -0.267, -1.942]}
                >
                  <mesh
                    name="Object_198"
                    geometry={nodes.Object_198.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Arm_2006_82"
                  position={[1.615, -1.566, -6.588]}
                  rotation={[3.135, -0.267, -1.942]}
                >
                  <mesh
                    name="Object_200"
                    geometry={nodes.Object_200.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Arm_2007_83"
                  position={[-39.672, -1.566, 36.747]}
                  rotation={[3.135, -0.267, -1.942]}
                >
                  <mesh
                    name="Object_202"
                    geometry={nodes.Object_202.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Arm_2008_84"
                  position={[50.316, -1.566, 43.875]}
                  rotation={[3.131, -0.899, -1.949]}
                >
                  <mesh
                    name="Object_204"
                    geometry={nodes.Object_204.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Arm_2009_85"
                  position={[1.974, -1.566, 55.836]}
                  rotation={[3.134, -0.627, -1.945]}
                >
                  <mesh
                    name="Object_206"
                    geometry={nodes.Object_206.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Body_1001_86"
                  position={[-52.854, 1.888, 3.054]}
                  rotation={[0.02, 0.346, -0.007]}
                >
                  <mesh
                    name="Object_208"
                    geometry={nodes.Object_208.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Body_1002_87"
                  position={[-70.461, 1.888, -30.814]}
                  rotation={[0.029, -0.864, 0.022]}
                >
                  <mesh
                    name="Object_210"
                    geometry={nodes.Object_210.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Body_1003_88"
                  position={[-65.271, 1.888, -55.998]}
                  rotation={[3.009, -1.426, 3.01]}
                >
                  <mesh
                    name="Object_212"
                    geometry={nodes.Object_212.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Body_1004_89"
                  position={[25.593, 1.888, -32.668]}
                  rotation={[3.009, -1.426, 3.01]}
                >
                  <mesh
                    name="Object_214"
                    geometry={nodes.Object_214.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Body_1005_90"
                  position={[49.549, 1.888, -57.385]}
                  rotation={[0.042, -1.101, 0.038]}
                >
                  <mesh
                    name="Object_216"
                    geometry={nodes.Object_216.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Body_1006_91"
                  position={[51.185, 1.888, -8.906]}
                  rotation={[2.981, -1.451, 2.982]}
                >
                  <mesh
                    name="Object_218"
                    geometry={nodes.Object_218.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Body_1007_92"
                  position={[55.091, 1.888, 10.448]}
                  rotation={[3.113, -0.853, 3.12]}
                >
                  <mesh
                    name="Object_220"
                    geometry={nodes.Object_220.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Body_1008_93"
                  position={[14.807, 1.888, -5.755]}
                  rotation={[3.122, 0.057, -3.141]}
                >
                  <mesh
                    name="Object_222"
                    geometry={nodes.Object_222.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Body_1009_94"
                  position={[-16.237, 1.888, 31.186]}
                  rotation={[3.104, -1.037, 3.109]}
                >
                  <mesh
                    name="Object_224"
                    geometry={nodes.Object_224.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Body_1010_95"
                  position={[-54.261, 1.888, 19.264]}
                  rotation={[3.121, -0.359, 3.134]}
                >
                  <mesh
                    name="Object_226"
                    geometry={nodes.Object_226.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Body_1011_96"
                  position={[27.844, 1.888, 55.599]}
                  rotation={[3.081, 1.25, -3.084]}
                >
                  <mesh
                    name="Object_228"
                    geometry={nodes.Object_228.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Body_1012_97"
                  position={[57.694, 1.888, 68.524]}
                  rotation={[0.019, 0.082, -0.002]}
                >
                  <mesh
                    name="Object_230"
                    geometry={nodes.Object_230.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Body_1013_98"
                  position={[68.074, 1.888, 35.155]}
                  rotation={[0.047, 1.152, -0.043]}
                >
                  <mesh
                    name="Object_232"
                    geometry={nodes.Object_232.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Body_2001_99"
                  position={[-48.142, 1.455, -13.573]}
                  rotation={[-3.074, 0.733, -0.404]}
                >
                  <mesh
                    name="Object_234"
                    geometry={nodes.Object_234.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Body_2002_100"
                  position={[-46.862, 0.958, -56.564]}
                  rotation={[0.138, 0.766, -0.268]}
                >
                  <mesh
                    name="Object_236"
                    geometry={nodes.Object_236.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Body_2003_101"
                  position={[34.233, 0.958, -32.251]}
                  rotation={[0.221, -1.103, 0.026]}
                >
                  <mesh
                    name="Object_238"
                    geometry={nodes.Object_238.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Body_2004_102"
                  position={[15.113, 0.958, 4.389]}
                  rotation={[3.028, -0.505, 2.915]}
                >
                  <mesh
                    name="Object_240"
                    geometry={nodes.Object_240.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Body_2005_103"
                  position={[59.755, 0.958, 29.346]}
                  rotation={[2.999, 0.801, 3.073]}
                >
                  <mesh
                    name="Object_242"
                    geometry={nodes.Object_242.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Body_2006_104"
                  position={[18.749, 0.958, 57.876]}
                  rotation={[0.132, 0.72, -0.259]}
                >
                  <mesh
                    name="Object_244"
                    geometry={nodes.Object_244.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Body_2007_105"
                  position={[-5.153, 0.958, 29.555]}
                  rotation={[3.04, 0.204, 2.99]}
                >
                  <mesh
                    name="Object_246"
                    geometry={nodes.Object_246.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Body_2008_106"
                  position={[-53.135, 0.958, 28.684]}
                  rotation={[3.003, 0.774, 3.067]}
                >
                  <mesh
                    name="Object_248"
                    geometry={nodes.Object_248.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Body_2009_107"
                  position={[-60.365, 0.958, -33.267]}
                  rotation={[0.16, -0.897, -0.047]}
                >
                  <mesh
                    name="Object_250"
                    geometry={nodes.Object_250.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Body_2010_108"
                  position={[60.081, 0.958, -53.832]}
                  rotation={[0.106, -0.367, -0.134]}
                >
                  <mesh
                    name="Object_252"
                    geometry={nodes.Object_252.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Body_2011_109"
                  position={[58.722, 0.958, -9.141]}
                  rotation={[0.446, -1.339, 0.264]}
                >
                  <mesh
                    name="Object_254"
                    geometry={nodes.Object_254.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Body_2012_110"
                  position={[63.691, 0.958, 14.883]}
                  rotation={[0.409, -1.319, 0.225]}
                >
                  <mesh
                    name="Object_256"
                    geometry={nodes.Object_256.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Body_2013_111"
                  position={[54.644, 0.958, 58.13]}
                  rotation={[0.409, -1.319, 0.225]}
                >
                  <mesh
                    name="Object_258"
                    geometry={nodes.Object_258.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Head003_112"
                  position={[-52.313, 1.248, -44.874]}
                  rotation={[2.806, 1.303, 0.239]}
                >
                  <mesh
                    name="Object_260"
                    geometry={nodes.Object_260.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Head004_113"
                  position={[41.745, 1.248, -65.852]}
                  rotation={[0.099, 0.482, 3.01]}
                >
                  <mesh
                    name="Object_262"
                    geometry={nodes.Object_262.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Head005_114"
                  position={[-22.945, 1.248, 36.026]}
                  rotation={[0.099, 0.482, 3.01]}
                >
                  <mesh
                    name="Object_264"
                    geometry={nodes.Object_264.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Head006_115"
                  position={[45.004, 1.248, 38.824]}
                  rotation={[0.099, 0.482, 3.01]}
                >
                  <mesh
                    name="Object_266"
                    geometry={nodes.Object_266.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Head007_116"
                  position={[-54.276, 1.415, 9.184]}
                  rotation={[-2.454, -1.242, -2.535]}
                >
                  <mesh
                    name="Object_268"
                    geometry={nodes.Object_268.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Head008_117"
                  position={[12.136, 1.415, 45.059]}
                  rotation={[-0.308, -0.827, -0.284]}
                >
                  <mesh
                    name="Object_270"
                    geometry={nodes.Object_270.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Head009_118"
                  position={[57.686, 1.415, 2.526]}
                  rotation={[-0.308, -0.827, -0.284]}
                >
                  <mesh
                    name="Object_272"
                    geometry={nodes.Object_272.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Head010_119"
                  position={[24.912, 1.415, 13.995]}
                  rotation={[-0.235, -0.491, -0.166]}
                >
                  <mesh
                    name="Object_274"
                    geometry={nodes.Object_274.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Head011_120"
                  position={[-46.873, 1.469, 33.064]}
                  rotation={[-Math.PI / 2, -1.297, Math.PI]}
                >
                  <mesh
                    name="Object_276"
                    geometry={nodes.Object_276.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Head012_121"
                  position={[46.27, 1.469, 56.833]}
                  rotation={[-Math.PI / 2, -1.297, Math.PI]}
                >
                  <mesh
                    name="Object_278"
                    geometry={nodes.Object_278.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Head013_122"
                  position={[36.288, 1.469, -25.155]}
                  rotation={[-Math.PI / 2, -1.297, Math.PI]}
                >
                  <mesh
                    name="Object_280"
                    geometry={nodes.Object_280.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Pedestal_1001_123"
                  position={[-64.479, 0, 22.907]}
                  rotation={[Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Object_282"
                    geometry={nodes.Object_282.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                  <mesh
                    name="Object_283"
                    geometry={nodes.Object_283.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_Dest_Pedestal_1003_124"
                  position={[46.597, 0, 46.675]}
                  rotation={[Math.PI / 2, 0, -Math.PI]}
                >
                  <mesh
                    name="Object_285"
                    geometry={nodes.Object_285.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                  <mesh
                    name="Object_286"
                    geometry={nodes.Object_286.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_Dest_Pedestal_1004_125"
                  position={[70.269, 0, 1.156]}
                  rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                >
                  <mesh
                    name="Object_288"
                    geometry={nodes.Object_288.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                  <mesh
                    name="Object_289"
                    geometry={nodes.Object_289.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_Dest_Pedestal_1006_126"
                  position={[-41.487, 0, -68.346]}
                  rotation={[Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Object_291"
                    geometry={nodes.Object_291.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                  <mesh
                    name="Object_292"
                    geometry={nodes.Object_292.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_Dest_Pedestal_1007_127"
                  position={[27.347, 0, -44.901]}
                  rotation={[Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Object_294"
                    geometry={nodes.Object_294.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                  <mesh
                    name="Object_295"
                    geometry={nodes.Object_295.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_Dest_Pedestal_1008_128"
                  position={[-64.524, 0, -21.898]}
                  rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                >
                  <mesh
                    name="Object_297"
                    geometry={nodes.Object_297.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                  <mesh
                    name="Object_298"
                    geometry={nodes.Object_298.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_Dest_Pedestal_2001_129"
                  position={[-40.581, 0, 1.611]}
                  rotation={[Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Object_300"
                    geometry={nodes.Object_300.geometry}
                    material={materials.Mat_Pedestal_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Pedestal_2002_130"
                  position={[24.637, 0, 66.234]}
                  rotation={[Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Object_302"
                    geometry={nodes.Object_302.geometry}
                    material={materials.Mat_Pedestal_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Pedestal_2007_131"
                  position={[-65.71, 0, -44.752]}
                  rotation={[Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Object_304"
                    geometry={nodes.Object_304.geometry}
                    material={materials.Mat_Pedestal_destroyed}
                  />
                </group>
                <group
                  name="Statue_Dest_Pedestal_3002_132"
                  position={[-5.284, 0, 48.079]}
                  rotation={[Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Object_306"
                    geometry={nodes.Object_306.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                  <mesh
                    name="Object_307"
                    geometry={nodes.Object_307.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_Dest_Pedestal_3003_133"
                  position={[68.2, 0, 66.541]}
                  rotation={[Math.PI / 2, 0, Math.PI / 2]}
                >
                  <mesh
                    name="Object_309"
                    geometry={nodes.Object_309.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                  <mesh
                    name="Object_310"
                    geometry={nodes.Object_310.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_Dest_Pedestal_3004_134"
                  position={[68.583, 0, 24.178]}
                  rotation={[Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Object_312"
                    geometry={nodes.Object_312.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                  <mesh
                    name="Object_313"
                    geometry={nodes.Object_313.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_Dest_Pedestal_3005_135"
                  position={[26.754, 0, 2.175]}
                  rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                >
                  <mesh
                    name="Object_315"
                    geometry={nodes.Object_315.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                  <mesh
                    name="Object_316"
                    geometry={nodes.Object_316.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Statue_Dest_Pedestal_3007_136"
                  position={[71.067, 0, -68.872]}
                  rotation={[Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Object_318"
                    geometry={nodes.Object_318.geometry}
                    material={materials.Material_Statue_1_destroyed}
                  />
                  <mesh
                    name="Object_319"
                    geometry={nodes.Object_319.geometry}
                    material={materials.Mat_Pedestal}
                  />
                </group>
                <group
                  name="Tomb_Stone_137"
                  position={[-61.809, 0, -11.288]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_321"
                    geometry={nodes.Object_321.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                <group
                  name="Tomb_Stone001_138"
                  position={[-56.331, 0, -57.227]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_323"
                    geometry={nodes.Object_323.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                <group
                  name="Tomb_Stone002_139"
                  position={[-32.423, 0, -67.941]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_325"
                    geometry={nodes.Object_325.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                <group
                  name="Tomb_Stone003_140"
                  position={[4.661, 0, -59.349]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_327"
                    geometry={nodes.Object_327.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                <group
                  name="Tomb_Stone004_141"
                  position={[-15.345, 0, -37.132]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_329"
                    geometry={nodes.Object_329.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                <group
                  name="Tomb_Stone005_142"
                  position={[-29.639, 0, -7.579]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_331"
                    geometry={nodes.Object_331.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                <group
                  name="Tomb_Stone006_143"
                  position={[-33.093, 0, 19.355]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_333"
                    geometry={nodes.Object_333.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                <group
                  name="Tomb_Stone007_144"
                  position={[-55.214, 0, 56.002]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_335"
                    geometry={nodes.Object_335.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                <group
                  name="Tomb_Stone008_145"
                  position={[-22.282, 0, 56.2]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_337"
                    geometry={nodes.Object_337.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                <group
                  name="Tomb_Stone009_146"
                  position={[14.079, 0, 32.473]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_339"
                    geometry={nodes.Object_339.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                <group
                  name="Tomb_Stone010_147"
                  position={[35.478, 0, 42.401]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_341"
                    geometry={nodes.Object_341.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                <group
                  name="Tomb_Stone011_148"
                  position={[34.842, 0, 62.913]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_343"
                    geometry={nodes.Object_343.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                <group
                  name="Tomb_Stone012_149"
                  position={[35.372, 0, 21.336]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_345"
                    geometry={nodes.Object_345.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                <group
                  name="Tomb_Stone013_150"
                  position={[59.343, 0, 38.187]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_347"
                    geometry={nodes.Object_347.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                <group
                  name="Tomb_Stone014_151"
                  position={[50.072, 0, 10.83]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_349"
                    geometry={nodes.Object_349.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                <group
                  name="Tomb_Stone015_152"
                  position={[40.36, 0, -10.985]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_351"
                    geometry={nodes.Object_351.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                <group
                  name="Tomb_Stone016_153"
                  position={[60.965, 0, -29.618]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_353"
                    geometry={nodes.Object_353.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                <group
                  name="Tomb_Stone017_154"
                  position={[37.648, 0, -42.183]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_355"
                    geometry={nodes.Object_355.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                <group
                  name="Tomb_Stone018_155"
                  position={[26.045, 0, -56.998]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_357"
                    geometry={nodes.Object_357.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                <group
                  name="Tomb_Stone019_156"
                  position={[9.584, 0, -59.281]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_359"
                    geometry={nodes.Object_359.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                <group
                  name="Tomb_Stone020_157"
                  position={[18.5, 0, -41.346]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_361"
                    geometry={nodes.Object_361.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                <group
                  name="Tomb_Stone021_158"
                  position={[-4.146, 0, -35.537]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_363"
                    geometry={nodes.Object_363.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                <group
                  name="Tomb_Stone022_159"
                  position={[4.859, 0, -24.728]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_365"
                    geometry={nodes.Object_365.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                <group
                  name="Tomb_Stone023_160"
                  position={[-7.655, 0, -19.302]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_367"
                    geometry={nodes.Object_367.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                <group
                  name="Tomb_Stone024_161"
                  position={[18.111, 0, -26.817]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_369"
                    geometry={nodes.Object_369.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                <group
                  name="Tomb_Stone025_162"
                  position={[-6.636, 0, -5.667]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_371"
                    geometry={nodes.Object_371.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                <group
                  name="Tomb_Stone026_163"
                  position={[13.887, 0, 3.319]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_373"
                    geometry={nodes.Object_373.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                <group
                  name="Tomb_Stone027_164"
                  position={[-8.158, 0, 7.214]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_375"
                    geometry={nodes.Object_375.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                <group
                  name="Tomb_Stone028_165"
                  position={[-8.671, 0, 26.052]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_377"
                    geometry={nodes.Object_377.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                <group
                  name="Tomb_Stone029_166"
                  position={[2.898, 0, 9.024]}
                  rotation={[Math.PI / 2, 0, -0.682]}
                >
                  <mesh
                    name="Object_379"
                    geometry={nodes.Object_379.geometry}
                    material={materials.material_tomb_stone}
                  />
                </group>
                {/* <group name="Wall_167" rotation={[Math.PI / 2, 0, 0]}>
                  <mesh name="Object_381" geometry={nodes.Object_381.geometry} material={materials.Mat_Wall_Underground} />
                </group> */}
                <mesh
                  name="Object_14"
                  geometry={nodes.Object_14.geometry}
                  material={materials.material_0}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/ep9/exegol/exegol_descent.glb");
