/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/models/jediFighter/scene.gltf 
Author: Petri Liuhto (https://sketchfab.com/petri.liuhto)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/jedi-star-fighter-0b641c2f2b854f1f9ae7f2a731e44dbd
Title: Jedi Star Fighter
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function JediFighter(props) {
  const { nodes, materials } = useGLTF('./models/jediFighter/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.main_jsf_mainMat_0.geometry} material={materials.jsf_mainMat} />
        <mesh geometry={nodes.main_jsf_mainMat_0_1.geometry} material={materials.jsf_mainMat} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.aux_jsf_auxMat_0.geometry} material={materials.jsf_auxMat} />
        <mesh geometry={nodes.aux_jsf_auxMat_0_1.geometry} material={materials.jsf_auxMat} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/jediFighter/scene.gltf')
