/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/models/orbit/star_wars_orbit.glb 
Author: Neut2000 (https://sketchfab.com/Neut2000)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/star-wars-battlefront-2-cis-lucrehulk-ab556c91521444f48954e45e5f4b89e6
Title: Star Wars Battlefront 2 CIS Lucrehulk
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'

export function Orbit(props) {
  const { nodes, materials } = useGLTF('./models/ep1/orbit/star_wars_orbit.glb')
  const [modelLoaded, setModelLoaded] = useState(false);

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Shape.019']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Shape.020']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Shape.021']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Shape.022']} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/ep1/orbit/star_wars_orbit.glb')
