/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/models/tatooine/tatooine.glb 
Author: efaz3 (https://sketchfab.com/efaz3)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tatooine-b871789cd77a4e2ab9a9a06de41b67ea
Title: Tatooine
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'

export function Tatooine(props) {
  const { nodes, materials } = useGLTF('./models/ep1/tatooine/tatooine.glb')
  const [modelLoaded, setModelLoaded] = useState(false);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Material} rotation={[2.456, 0.972, 1.617]} />
    </group>
  )
}

useGLTF.preload('./models/ep1/tatooine/tatooine.glb')
