/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/models/ep8/snoke/snoke.glb 
Author: KevBot (https://sketchfab.com/boyle.kj)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/supreme-leader-snoke-disney-infinity-83e13bce1624406ab0ebddacf8e455b4
Title: Supreme Leader Snoke Disney Infinity
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Snoke(props) {
  const { nodes, materials } = useGLTF('./models/ep8/snoke/snoke.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./models/ep8/snoke/snoke.glb')
